[build]
builder = "docker"
dockerfilePath = "backend/Dockerfile"
context = "backend"

[deploy]
startCommand = "entrypoint.sh"

[[services]]
name = "api"
path = "backend"

[[services]]
name = "frontend"
path = "frontend"
