[build]
builder = "docker"
dockerfile = "Dockerfile"

[deploy]
startCommand = "entrypoint.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
maxRestartCount = 3
